apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: mcshares-service
  name: mcshares-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcshares-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mcshares-service
    spec:
      containers:
      - image: pranawmadubdocker/mcshares-service:1.0.0.RELEASE
        imagePullPolicy: IfNotPresent
        name: mcshares-service
        envFrom:
          - configMapRef:
              name: mcshares-service
      restartPolicy: Always
      securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mcshares-service
  name: mcshares-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mcshares-service
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  API_SECURITY_FILTER: "true"
kind: ConfigMap
metadata:
  name: mcshares-service
  namespace: default